// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * D​i​s​t​a​n​c​e​ ​C​a​l​c​u​l​a​t​o​r
	 */
	title: string
	/**
	 * P​r​o​t​o​t​y​p​e​ ​w​e​b​ ​a​p​p​l​i​c​a​t​i​o​n​ ​f​o​r​ ​c​a​l​c​u​l​a​t​i​n​g​ ​t​h​e​ ​d​i​s​t​a​n​c​e​ ​b​e​t​w​e​e​n​ ​a​d​d​r​e​s​s​e​s​.
	 */
	calcDescription: string
	/**
	 * S​o​u​r​c​e​ ​A​d​d​r​e​s​s
	 */
	source: string
	/**
	 * D​e​s​t​i​n​a​t​i​o​n​ ​A​d​d​r​e​s​s
	 */
	destination: string
	/**
	 * U​n​i​t
	 */
	unit: string
	/**
	 * D​i​s​t​a​n​c​e
	 */
	distance: string
	/**
	 * C​a​l​c​u​l​a​t​e​ ​D​i​s​t​a​n​c​e
	 */
	calcDistance: string
	/**
	 * V​i​e​w​ ​H​i​s​t​o​r​i​c​a​l​ ​Q​u​e​r​i​e​s
	 */
	viewHist: string
	/**
	 * M​i​l​e​s
	 */
	miles: string
	/**
	 * K​i​l​o​m​e​t​e​r​s
	 */
	kilo: string
	/**
	 * B​o​t​h
	 */
	both: string
	/**
	 * H​i​s​t​o​r​i​c​a​l​ ​Q​u​e​r​i​e​s
	 */
	histQueries: string
	/**
	 * H​i​s​t​o​r​y​ ​o​f​ ​u​s​e​r​'​s​ ​q​u​e​r​i​e​s​.
	 */
	histDescription: string
	/**
	 * D​i​s​t​a​n​c​e​ ​i​n​ ​M​i​l​e​s
	 */
	distMiles: string
	/**
	 * D​i​s​t​a​n​c​e​ ​i​n​ ​K​i​l​o​m​e​t​e​r​s
	 */
	distKilo: string
	/**
	 * B​a​c​k​ ​t​o​ ​C​a​l​c​u​l​a​t​o​r
	 */
	backToCalc: string
	/**
	 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​ ​a​n​d​ ​t​h​e​ ​c​a​l​c​u​l​a​t​i​o​n​ ​f​a​i​l​e​d​.
	 */
	wrongMessage: string
	/**
	 * C​a​l​c​u​l​a​t​i​o​n​ ​F​a​i​l​e​d
	 */
	calculationFailed: string
}

export type TranslationFunctions = {
	/**
	 * Distance Calculator
	 */
	title: () => LocalizedString
	/**
	 * Prototype web application for calculating the distance between addresses.
	 */
	calcDescription: () => LocalizedString
	/**
	 * Source Address
	 */
	source: () => LocalizedString
	/**
	 * Destination Address
	 */
	destination: () => LocalizedString
	/**
	 * Unit
	 */
	unit: () => LocalizedString
	/**
	 * Distance
	 */
	distance: () => LocalizedString
	/**
	 * Calculate Distance
	 */
	calcDistance: () => LocalizedString
	/**
	 * View Historical Queries
	 */
	viewHist: () => LocalizedString
	/**
	 * Miles
	 */
	miles: () => LocalizedString
	/**
	 * Kilometers
	 */
	kilo: () => LocalizedString
	/**
	 * Both
	 */
	both: () => LocalizedString
	/**
	 * Historical Queries
	 */
	histQueries: () => LocalizedString
	/**
	 * History of user's queries.
	 */
	histDescription: () => LocalizedString
	/**
	 * Distance in Miles
	 */
	distMiles: () => LocalizedString
	/**
	 * Distance in Kilometers
	 */
	distKilo: () => LocalizedString
	/**
	 * Back to Calculator
	 */
	backToCalc: () => LocalizedString
	/**
	 * Something went wrong and the calculation failed.
	 */
	wrongMessage: () => LocalizedString
	/**
	 * Calculation Failed
	 */
	calculationFailed: () => LocalizedString
}

export type Formatters = {}
